#!/usr/bin/env php
<?php
/**
 * Tigger, a PHP vTiger cli tool for tracking tickets and entering time
 * @author Ben Lake <me@benlake.org>
 * @license GNU Public License v3 (http://opensource.org/licenses/gpl-3.0.html)
 * @copyright Copyright (c) 2011, Ben Lake
 * @link https://github.com/benlake/tigger
 *
 * This file is part of the Tigger project.
 *
 * Tigger is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Tigger is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Tigger.  If not, see <http://www.gnu.org/licenses/>.
 */

// just an execute wrapper so we look like a "real" program
// and not a sketchy .php file
require_once(dirname(__FILE__).'/tigger.php');